### ISSUE TITLE
Refactor deprecated APIs into bundled plugin

### ISSUE THREAD

**Issue by invisnet** [ClassicPress/ClassicPress_Deprecated#10]
There's a huge amount of redundant code that can be moved into a bundled plugin. It can't just be deleted because there are sites still using it, but it doesn't need to be in core.

**Comment by scottybo** [comment]
Interesting idea! Would you be open to speccing this out in more detail so that we can understand your thoughts in a bit more detail?

**Comment by invisnet** [comment]
Sure. Let's take a simple example: `wp-includes/ms-deprecated.php`; the whole file can go into a plugin. Same for `wp-includes/customize/class-wp-customize-new-menu-section.php`. And `wp-includes/theme-compat/comments.php`. There are many more. Depending on usage some might need stubs left in core (IIRC there was a requirement to include some files directly in WP3).

After that there are deprecated functions, e.g. `is_comments_popup()` in `wp-includes/class-wp-query.php`. That would take a little more work to move, but still perfectly sensible.

In an ideal world there'd be 3 plugins - `wp-compat-2.x` for sites needing WP2 functions containing everything deprecated in 3.x, and `wp-compat-3.x` and `wp-compat-4.x` on the same basis. However, given that some functions were deprecated on a point release this might be more trouble than it's worth - the only way to find out is to try it.

**Comment by scottybo** [comment]
Closed for now - this will be opened for a public vote in the future :)
