### ISSUE TITLE
Will this be just a fork of WP or will it be improved in any way?

### ISSUE THREAD

**Issue by dingo-d** [ClassicPress/ClassicPress_Deprecated#14]
I'm just wondering what is the ultimate goal of this project? Are you going to just keep the state of the WP as it is now (4.9.8 or 4.9.7 version) and only patch certain security features, or will you clean the codebase and make it more modern?

The thing that is really hampering the progress of WordPress (in my opinion) is this hell-bent backward compatibility. Everything has to work on PHP 5.2 which is ridiculous (not to mention the benefits to the performance PHP 7+ gives).

So will you be cleaning the code to make it more _modern_? Add namespace to avoid possible conflicts, use composer and autoloading, removing outdated scripts (jQuery 1.2 in 2018). Things like that.

**Comment by scottybo** [comment]
The short answer is yes, we will! Our first priority is creating a stable fork, then we will be changing to community led development.

Please note this repo will be closed as we're moving to https://github.com/ClassicPress/ClassicPress

**Comment by dingo-d** [comment]
Thanks for the answer. I'm looking forward to seeing how this unravels :)
