### ISSUE TITLE
Rename WordPress to ClassicPress

### ISSUE THREAD

**Issue by ClassicPress** [ClassicPress/ClassicPress_Deprecated#3]
We need to rename WordPress to ClassicPress in all "public" areas (this includes the admin area). 

However, **we will not** (at this stage anyway):

- Change any variable names UNLESS they contain the word WordPress
- Change any class or function names UNLESS they contain the word WordPress

**Comment by RiaanKnoetze** [comment]
"WordPress" is trademarked though. Doesn't that apply to references in the code as well?

**Comment by ClassicPress** [comment]
Hm, good point - will update this issue

**Comment by scottybo** [comment]
Closed and moved to https://github.com/ClassicPress/ClassicPress-v1/issues/263
