### ISSUE TITLE
Please remove Hello Dolly :)

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress_Deprecated#9]
Great initiative, if there is ever a good timing then this is it!

As per title, ClassicPress should not bundle any plugins imo.

By the way, I'm willing to contribute in any way I can.

Good luck!

**Comment by scottybo** [comment]
Completely agree - Akismet and Hello Dolly are always the first things I remove after installing WordPress.

**Comment by scottybo** [comment]
Updated - this will be opened to a public vote in the future :)
